alias msf="sudo mount -t vboxsf Virtualbox_Shared_Folder /home/zubieta/VBShared/"
alias ipnb="cd ~/Documents/Notebooks && ipython notebook --pylab=inline"
alias reload="source ~/.bashrc"
alias quit="exit"
alias upk="sudo apt-get update"
alias ipk="sudo apt-get install"
alias gpk="sudo apt-get upgrade"
alias spk="apt-cache search"
alias rpk="sudo apt-get remove"
alias ppk="sudo apt-get autoremove"
alias cch="sudo apt-get autoclean"
