alias msf="sudo mount -t vboxsf Virtualbox_Shared_Folder ~/VBShared/"
alias ipnb="ipython notebook --pylab=inline --profile='base16-railscasts-dark'"
alias reload="source ~/.bashrc"
alias quit="exit"
alias upk="sudo apt-get update"
alias ipk="sudo apt-get install"
alias gpk="sudo apt-get upgrade"
alias spk="apt-cache search"
alias rpk="sudo apt-get remove"
alias ppk="sudo apt-get autoremove"
alias cch="sudo apt-get autoclean"
alias md="mkdir -p"
alias rf="rm -rf"
alias xclip="xclip -selection clipboard"
alias clipin="xclip -selection clipboard -i"
alias clipout="xclip -selection clipboard -o"
alias eping="ping eff.org -c3"
alias fping="ping fsf.org -c3"
alias gping="ping google.com -c3"
alias diff="colordiff"
alias gtype="gtypist esp.typ"
alias calc="gnome-calculator -s"
alias sound="gnome-control-center sound"
alias feh="feh --keep-zoom-vp -. -B black -q"
alias m="ncmpcpp"
alias nless="less -N"
alias netmon="speedometer -r eth0 -t eth0"
alias ntop="speedometer -r eth0 -t eth0"
alias netmon2="nload -t 500"
alias yt="mpsyt"
alias pup-install="pip install --user --proxy=$https_proxy"
alias pup-upgrade="pip install -U --user --proxy=$https_proxy"
#alias pup-upgrade-all="for PACK in $(pip list --outdated | grep -v '^Could\|Some' | cut -d' ' -f1); do if [[ $(pip show $PACK | grep Location | grep site-packages | grep $USER) ]]; then pip install -U --user --proxy=$https_proxy $PACK; fi; done)"
alias pup-remove="pip uninstall"
alias pup3-install="pip3 install --user --proxy=$https_proxy"
alias pup3-upgrade="pip3 install -U --user --proxy=$https_proxy"
#alias pup3-upgrade-all="for PACK in $(pip3 list --outdated --proxy=$https_proxy | grep -v '^Could\|Some' | cut -d' ' -f1); do if [[ $(pip3 show $PACK | grep Location | grep site-packages | grep $USER) ]]; then pip3 install -U --user --proxy=$https_proxy $PACK; fi; done)"
alias pup3-remove="pip3 uninstall"
